"""Generate the single-file deployable contract.

GenLayer deploys exactly one Python file. `genlayer deploy --contract` reads a
single path and performs no module bundling, so a local `import vouch_core`
has nothing to resolve against on-chain. The library modules under `lib/` are
therefore inlined into marked regions of `contracts/vouch.py`, which
is the one and only artifact that gets deployed.

`lib/vouch_core.py`, `lib/vouch_evidence.py` and `lib/vouch_prompts.py` remain the source of truth: they
are what the test suite imports and what a reader should edit. They are build
inputs, not contracts -- neither declares a contract class, and neither is ever
deployed or linted as one. Everything between the INLINE markers is
machine-managed.

Run after any change to either library module:

    python tools/build_contract.py

`tests/test_contract_sync.py` fails if the checked-in contract is stale, so
drift cannot reach a reviewer or a deployment unnoticed.
"""

from __future__ import annotations

import argparse
import ast
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "vouch.py"
LIB = ROOT / "lib"
MODULES = ("vouch_core.py", "vouch_evidence.py", "vouch_prompts.py")

BEGIN = "# >>> BEGIN INLINE {name} - generated by build_contract.py, do not edit"
END = "# <<< END INLINE {name}"


def library_body(path: pathlib.Path) -> str:
    """Return a module's source with its docstring and import prologue removed.

    The imports are dropped because the generated contract hoists the union of
    them into a single block; everything from the first real statement onward
    is carried over verbatim, comments included.
    """
    src = path.read_text(encoding="utf-8")
    lines = src.splitlines()

    start: int | None = None
    for node in ast.parse(src).body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if (
            isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            continue  # module docstring
        # A decorated definition starts at its first decorator, not at `def`.
        start = min([node.lineno] + [d.lineno for d in getattr(node, "decorator_list", [])]) - 1
        break

    if start is None:
        raise SystemExit(f"{path.name}: no inlinable body found")

    return "\n".join(lines[start:]).strip("\n")


def render() -> str:
    """Return what `vouch.py` should contain right now.

    Reads the contract as its own template: the hand-written contract code
    lives outside the markers and is preserved, while each marked region is
    refilled from the corresponding library module.
    """
    text = CONTRACT.read_text(encoding="utf-8")

    for name in MODULES:
        begin, end = BEGIN.format(name=name), END.format(name=name)
        if begin not in text or end not in text:
            raise SystemExit(f"{CONTRACT.name}: missing INLINE markers for {name}")

        head, rest = text.split(begin, 1)
        _, tail = rest.split(end, 1)
        body = library_body(LIB / name)
        text = f"{head}{begin}\n\n{body}\n\n{end}{tail}"

    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the contract is stale instead of rewriting it",
    )
    args = parser.parse_args()

    want = render()
    have = CONTRACT.read_text(encoding="utf-8")

    if want == have:
        print(f"{CONTRACT.name} is up to date")
        return 0

    if args.check:
        print(
            f"{CONTRACT.name} is STALE - run `python tools/build_contract.py`",
            file=sys.stderr,
        )
        return 1

    CONTRACT.write_text(want, encoding="utf-8", newline="\n")
    print(f"{CONTRACT.name} regenerated from {', '.join(MODULES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
